server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

aws:
  region: us-east-1
  s3:
    url: http://127.0.0.1:4566
    access-key: localstack
    secret-key: localstack
    images:
      bucket-name: images
      max-size: 256
    files:
      bucket-name: files
      max-size: 256

token:
  signing-key: bgM8ZUALPlm4nij35kFx1dp1yRzL4aAvsvWwrGlykx9T05Lgt7J53kaJ6BzbozNsGIQJR71n5NGzljd4Ae3wWhdSUnAkFIdIXCQmnkMlRvx1RwxMj3pQeArUg2K5eAhcNSPjTxthVslTemwO2GMRnm01HQPOa9R8m5fWuFdma3G1ZElZ0n8ctQ4n7KeZTLAhzMg5qSpNr2MrgkTYfrE9ci2VreGKMBo5O4TFyK52kY5m6HvlOCmcfZ5D8346KlJ